const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#2f95dc",
    background: "#ffffff",
    foreground: "#0a0a0a",
    card: "#f9f9f9",
    cardForeground: "#0a0a0a",
    primary: "#2f95dc",
    primaryForeground: "#ffffff",
    secondary: "#f0f0f0",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f0f0",
    mutedForeground: "#737373",
    accent: "#f0f0f0",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e5e5e5",
    input: "#e5e5e5",
  },
  dark: {
    text: "#ffffff",
    tint: "#3b9eff",
    background: "#000000",
    foreground: "#ffffff",
    card: "#111111",
    cardForeground: "#ffffff",
    primary: "#3b9eff",
    primaryForeground: "#000000",
    secondary: "#1a1a1a",
    secondaryForeground: "#ffffff",
    muted: "#1a1a1a",
    mutedForeground: "#888888",
    accent: "#1a2a3a",
    accentForeground: "#3b9eff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#222222",
    input: "#222222",
  },
  radius: 12,
};

export default colors;
